apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: LoadBalencer
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    nodePort: 30300
    port: 8080
    targetPort: 8080
    
